### ISSUE TITLE
Input for Selection Area should accept full coord strings

### ISSUE THREAD

**Issue by StuartDA** [JamesMCo/toolets#13]
Should be able to input full coord strings into an input box and not have to split it up.

Reason:
This will allow for faster input and output on using the tool as we don't have to spit the coord string into 3 input boxes and instead would only need to input it into one box.

Why: This will increase the ease of the tool as it should make inputting faster and easier into the tool.

**Comment by JamesMCo** [comment]
I've had a go at this in #18, could you [take a look](https://mrjamesco.uk/toolets/selarea/) and see if I've understood properly what you're asking for? :)
